const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const core = require('../src/core.js');
const seconds = 1791047730;
const message = { id: 'user-1', create_time: seconds, author: { role: 'user' }, content: { parts: ['private text'] } };


test('module互換オブジェクトがあるページでも共通処理をブラウザ側へ公開する', () => {
  const context = { module: { exports: {} } };
  vm.runInNewContext(fs.readFileSync('src/core.js', 'utf8'), context);
  assert.equal(typeof context.ChatGPTTimeMarkCore?.messageId, 'function');
  assert.equal(context.module.exports, context.ChatGPTTimeMarkCore);
});

test('表示用配布ファイルは共通処理と表示処理を順に含む', () => {
  const expected = '// Generated by node scripts/build.cjs.\n' + ['src/core.js', 'src/content.js'].map(file => fs.readFileSync(file, 'utf8')).join('\n');
  assert.equal(fs.readFileSync('src/content-runtime.js', 'utf8'), expected);
  const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
  assert.deepEqual(manifest.content_scripts.find(script => script.world === 'ISOLATED').js, ['src/content-runtime.js']);
});

test('React取得は現在のツリーでIDが一致する投稿だけを返す', () => {
  const state = {};
  const root = { tag: 3, stateNode: state };
  state.current = root;
  const staleRoot = { tag: 3, stateNode: state };
  const current = { memoizedProps: { messages: [message] }, return: root };
  root.child = current;
  const stale = { memoizedProps: { messages: [{ ...message, create_time: seconds - 60 }] }, return: staleRoot, alternate: current };
  const element = { matches: () => true, getAttribute: () => message.id, '__reactFiber$test': stale };
  assert.deepEqual(core.reactRecord(element), { id: message.id, seconds });
  element.getAttribute = () => 'different';
  assert.equal(core.reactRecord(element), null);
  element.getAttribute = () => message.id;
  current.memoizedProps.messages = [{ ...message, author: { role: 'assistant' } }];
  assert.equal(core.reactRecord(element), null);
  current.return = current;
  assert.equal(core.reactRecord(element), null);
});

test('現行React構造は会話と表示ターンが一致するスナップショットから取得する', () => {
  const turn = { items: [{ type: 'user-message', messageId: message.id }] };
  const entry = { id: 'turn-1', conversationId: 'conversation-1', turn };
  const snapshot = { renderedConversation: { mapping: { [message.id]: { id: message.id, message } } }, renderedTurns: [entry] };
  const root = { tag: 3, stateNode: {} };
  root.stateNode.current = root;
  const owner = { memoizedProps: { conversationId: entry.conversationId }, memoizedState: { memoizedState: [snapshot] }, return: root };
  const row = { memoizedProps: { entry }, return: owner };
  root.child = owner; owner.child = row;
  const element = { matches: () => true, getAttribute: () => message.id, '__reactFiber$new': row };
  assert.deepEqual(core.reactRecord(element, entry.conversationId), { id: message.id, seconds });
  assert.equal(core.reactRecord(element, 'different-conversation'), null);
  snapshot.renderedTurns = [{ ...entry, turn: { ...turn } }];
  assert.equal(core.reactRecord(element, entry.conversationId), null);
  snapshot.renderedTurns = [entry];
  owner.memoizedState.next = { memoizedState: { ...snapshot, renderedConversation: { mapping: { [message.id]: { id: message.id, message: { ...message, create_time: seconds - 1 } } } } } };
  assert.equal(core.reactRecord(element, entry.conversationId), null);
  owner.memoizedState.next = null;
  owner.memoizedState.memoizedState = null;
  owner.updateQueue = { memoCache: { data: [[snapshot]] } };
  assert.deepEqual(core.reactRecord(element, entry.conversationId), { id: message.id, seconds });
});

test('会話データからユーザーIDと日時だけを返す', () => {
  assert.deepEqual(core.extract({ mapping: { a: { message }, b: { message: { ...message, id: 'assistant', author: { role: 'assistant' } } } } }), [{ id: 'user-1', seconds }]);
});
test('日時欠落・不正値・未来日時・不正IDは表示対象にしない', () => {
  for (const create_time of [null, undefined, '1791047730', NaN, Infinity, -1, 1791047730000]) {
    assert.deepEqual(core.extract({ message: { ...message, create_time } }), []);
    assert.equal(core.format(create_time), null);
  }
  assert.deepEqual(core.extract({ message: { ...message, id: '<script>' } }), []);
});
test('会話の日時をメッセージの日時として使用しない', () => {
  assert.deepEqual(core.extract({ create_time: seconds, mapping: { a: { message: { ...message, create_time: null } } } }), []);
});
test('現地時間の日時を秒までゼロ埋めする', () => {
  const local = new Date(2026, 0, 2, 3, 4, 5);
  assert.equal(core.format(local.getTime() / 1000), '2026/01/02 03:04:05');
});
test('分割されたCRLFストリームと複数行dataを処理する', () => {
  const output = [];
  const feed = core.streamParser(records => output.push(...records));
  const raw = `data: ${JSON.stringify({ type: 'input_message', input_message: message })}\r\n\r\n`;
  for (const char of raw) feed(char);
  feed('data: [DONE]\n\ndata: invalid\n\n');
  feed(`data: {"v":\ndata: ${JSON.stringify({ message })}}\n\n`);
  assert.deepEqual(output, [{ id: 'user-1', seconds }, { id: 'user-1', seconds }]);
});
test('過大ストリームを破棄し、その後の正常イベントを処理する', () => {
  const output = [];
  const feed = core.streamParser(records => output.push(...records));
  feed('x'.repeat(1024 * 1024 + 1));
  feed(`data: ${JSON.stringify({ message })}\n\n`);
  assert.deepEqual(output, [{ id: 'user-1', seconds }]);
});
test('fetchの元Promise・応答・本文を維持し追加リクエストをしない', async () => {
  const response = new Response(JSON.stringify({ mapping: { a: { message } } }));
  const originalPromise = Promise.resolve(response);
  const output = [];
  let calls = 0;
  const location = { pathname: '/c/abc', origin: 'https://chatgpt.com', href: 'https://chatgpt.com/c/abc' };
  const window = { fetch() { calls++; return originalPromise; }, postMessage(data) { output.push(data); }, addEventListener() {} };
  const context = { window, location, ChatGPTTimeMarkCore: core, Request, URL, TextDecoder, setTimeout, clearTimeout };
  vm.runInNewContext(fs.readFileSync('src/interceptor.js', 'utf8'), context);
  const result = window.fetch('/backend-api/conversation/12345678-1234-1234-1234-123456789012');
  assert.equal(result, originalPromise);
  assert.equal(await result, response);
  assert.equal((await response.json()).mapping.a.message.content.parts[0], 'private text');
  for (let i = 0; i < 20 && !output.length; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(calls, 1);
  assert.equal(output.length, 1);
  assert.equal(JSON.stringify(output).includes('private text'), false);
  assert.equal(output[0].records[0].id, message.id);
});
test('manifestはChatGPT限定で余分なAPI権限を持たない', () => {
  const manifest = JSON.parse(fs.readFileSync('manifest.json', 'utf8'));
  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.permissions, undefined);
  assert.equal(manifest.host_permissions, undefined);
  for (const script of manifest.content_scripts) {
    assert.deepEqual(script.matches, ['https://chatgpt.com/*']);
    assert.equal(script.all_frames, true, 'マルチViewの各ChatGPTフレームにも取得・表示を注入する');
    for (const file of [...script.js, ...(script.css || [])]) assert.equal(fs.existsSync(file), true);
  }
});

test('現行DOMではユーザーバブルに最も近いIDから照合し、曖昧なIDは使わない', () => {
  const bubble = {
    matches: () => false,
    closest: selector => selector === '[data-chatgpt-search-message-ids]' ? { getAttribute: () => 'current-user' } : null
  };
  assert.equal(core.messageId(bubble), 'current-user');
  bubble.closest = () => ({ getAttribute: () => 'user-a,user-b' });
  assert.equal(core.messageId(bubble), null);
  const legacy = { matches: () => true, getAttribute: () => 'legacy-user' };
  assert.equal(core.messageId(legacy), 'legacy-user');
});

test('表示処理は重複・ID変更・会話切替・他サイト由来の通知を扱う', () => {
  // Minimal DOM fixture: tests behavior without claiming a real-browser result.
  let handler;
  let mutate;
  const tasks = [];
  const location = { pathname: '/c/first', origin: 'https://chatgpt.com' };
  const user = {
    id: 'user-1', role: 'user', children: [],
    carrier: null,
    getAttribute(name) { return name === 'data-chatgpt-timestamp-record' ? this.carrier : this.id; },
    matches() { return this.role === 'user'; },
    querySelector() { return this.children[0] || null; },
    prepend(stamp) { this.children.unshift(stamp); stamp.parentElement = this; }
  };
  const document = {
    querySelectorAll(selector) { return selector.startsWith('time') ? [...user.children] : user.role === 'user' ? [user] : []; },
    createElement() { return { textContent: '', dateTime: '', setAttribute() {}, remove() { user.children = user.children.filter(x => x !== this); } }; }
  };
  const window = { addEventListener(type, listener) { if (type === 'message') handler = listener; }, postMessage() {} };
  vm.runInNewContext(fs.readFileSync('src/content.js', 'utf8'), {
    window, document, location, ChatGPTTimeMarkCore: core,
    setTimeout(fn) { tasks.push(fn); },
    MutationObserver: class { constructor(callback) { mutate = callback; } observe() {} }
  });
  const flush = () => { while (tasks.length) tasks.shift()(); };
  const notify = (records, route = location.pathname, origin = location.origin) => handler({ source: window, origin, data: { type: 'CHATGPT_TIMESTAMP_V1', route, records } });
  flush();
  assert.equal(user.children.length, 0);
  user.carrier = JSON.stringify({ id: user.id, seconds, route: location.pathname });
  mutate(); flush();
  assert.equal(user.children.length, 1);
  assert.equal(user.children[0].textContent, core.format(seconds));
  user.carrier = JSON.stringify({ id: user.id, seconds, firstSeconds: seconds - 60, versionCount: 2, route: location.pathname });
  mutate(); flush();
  assert.equal(user.children[0].textContent, core.format(seconds));
  user.carrier = JSON.stringify({ id: 'different-user', seconds, route: location.pathname });
  mutate(); flush();
  assert.equal(user.children.length, 0);
  user.carrier = JSON.stringify({ id: user.id, seconds, route: '/c/stale' });
  mutate(); flush();
  assert.equal(user.children.length, 0);
  user.carrier = null;
  notify([{ id: user.id, seconds }], location.pathname, 'https://example.com'); flush();
  assert.equal(user.children.length, 0);
  notify([{ id: user.id, seconds }]); flush();
  assert.equal(user.children.length, 1);
  assert.equal(user.children[0].textContent, core.format(seconds));
  notify([{ id: user.id, seconds }]); mutate(); flush();
  assert.equal(user.children.length, 1);
  user.id = 'edited-user'; mutate(); flush();
  assert.equal(user.children.length, 0);
  notify([{ id: user.id, seconds }]); flush();
  user.role = 'assistant'; mutate(); flush();
  assert.equal(user.children.length, 0);
  user.role = 'user';
  location.pathname = '/c/second'; mutate(); flush();
  assert.equal(user.children.length, 0);
  notify([{ id: user.id, seconds }], '/c/first'); flush();
  assert.equal(user.children.length, 0);
});

test('DOTS会話だけを対象にし入口や通常会話にはAI表示を拡張しない', () => {
  assert.equal(core.isDotsRoute('/dots/dot-1'), true);
  assert.equal(core.isDotsRoute('/dots/dot-1/'), true);
  for (const route of ['/dots/', '/c/chat-1', '/dots/dot-1/settings', '/other/dots/dot-1']) assert.equal(core.isDotsRoute(route), false);
});

test('DOTS用React取得は一致するAIの実日時だけを返し本文は返さない', () => {
  const ai = { ...message, author: { role: 'assistant' } };
  const root = { tag: 3, stateNode: {} }; root.stateNode.current = root;
  const row = { memoizedProps: { messages: [ai] }, return: root }; root.child = row;
  const element = { matches: selector => selector.includes('assistant'), closest: () => null, getAttribute: () => ai.id, '__reactFiber$dots': row };
  assert.equal(core.reactRecord(element, 'dot-1'), null);
  assert.deepEqual(core.reactRecord(element, 'dot-1', true), { id: ai.id, seconds });
  row.memoizedProps.messages = [{ ...ai, create_time: null }];
  assert.equal(core.reactRecord(element, 'dot-1', true), null);
  row.memoizedProps.messages = [{ ...ai, id: 'other-message' }];
  assert.equal(core.reactRecord(element, 'dot-1', true), null);
});