const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = ['src/core.js', 'src/content.js']
  .map(file => fs.readFileSync(path.join(root, file), 'utf8')).join('\n');
fs.writeFileSync(path.join(root, 'src/content-runtime.js'), '// Generated by node scripts/build.cjs.\n' + source);
